POST http://localhost:3000/api/v1/messaging/email/send HTTP/1.1
Content-Type: application/json

{
  "email": "katanyoo@infiltech.org",
  "subject": "ทดสอบ",
  "bodyText": "<a href='https://infiltech.org'>link</a>"
}
